% JN Kather 2018-2020
% This is part of the DeepHistology repository
% License: see separate LICENSE file 
% 
% documentation for this function:
% this function returns hard coded default training options

function opts = getTrainingOptions(hyperprm,imdsVAL)

if isempty(imdsVAL) % without internal validation
     opts = trainingOptions('adam',...
    'InitialLearnRate',hyperprm.InitialLearnRate,...
    'L2Regularization',hyperprm.L2Regularization,... 		
    'MiniBatchSize',hyperprm.MiniBatchSize,...			
    'MaxEpochs',hyperprm.MaxEpochs,...			
    'ExecutionEnvironment',hyperprm.ExecutionEnvironment,...
    'VerboseFrequency',50,...
    'GradientDecayFactor',hyperprm.GradientDecayFactor,...
    'Epsilon',hyperprm.Epsilon,...    
    'DispatchInBackground',hyperprm.DispatchInBackground,... 
    'Plots','none');   
else   % with internal validation
     opts = trainingOptions('adam',...
    'InitialLearnRate',hyperprm.InitialLearnRate,...
    'L2Regularization',hyperprm.L2Regularization,... 		
    'MiniBatchSize',hyperprm.MiniBatchSize,...			
    'MaxEpochs',hyperprm.MaxEpochs,...			
    'ExecutionEnvironment',hyperprm.ExecutionEnvironment,...
    'ValidationFrequency',hyperprm.ValidationFrequency,...
    'ValidationPatience',hyperprm.ValidationPatience,...
    'ValidationData',imdsVAL,...
    'VerboseFrequency',50,...
    'GradientDecayFactor',hyperprm.GradientDecayFactor,...
    'Epsilon',hyperprm.Epsilon,...    
    'DispatchInBackground',hyperprm.DispatchInBackground,... 
    'Plots','none');   
end
end
