function opts = getTrainingOptions(hyperprm,imds_validation)

if isempty(imds_validation) % if there is no validation set
opts = trainingOptions('adam',...
    'InitialLearnRate',hyperprm.InitialLearnRate,...
    'L2Regularization',hyperprm.L2Regularization,... 		
    'MiniBatchSize',hyperprm.MiniBatchSize,...			
    'MaxEpochs',hyperprm.MaxEpochs,...			
    'ExecutionEnvironment',hyperprm.ExecutionEnvironment,...
    'VerboseFrequency',50,...
    'Plots','none');   
else  % if there is a validation set
opts = trainingOptions('adam',...
    'InitialLearnRate',hyperprm.InitialLearnRate,...
    'ValidationData',imds_validation,...		
    'ValidationFrequency',hyperprm.ValidationFrequency,...
    'ValidationPatience',hyperprm.ValidationPatience,...
    'L2Regularization',hyperprm.L2Regularization,... 		
    'MiniBatchSize',hyperprm.MiniBatchSize,...			
    'MaxEpochs',hyperprm.MaxEpochs,...				
    'ExecutionEnvironment',hyperprm.ExecutionEnvironment,...
    'VerboseFrequency',50,...
    'Plots','none');
end

end
